version: 2
jobs:
  setup:
    docker:
      - image: circleci/node:10
    working_directory: ~/application
    steps:
      - checkout
      - restore_cache:
          keys:
            - yarn-cache-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn install
      - save_cache:
          key: yarn-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - save_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
          paths:
            - ~/application
  build:
    docker:
      - image: circleci/node:10
    working_directory: ~/application
    steps:
      - restore_cache:
          key: v1-repo-{{ .Environment.CIRCLE_SHA1 }}
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Gatsby Build
          command: yarn build
      - run:
          name: GH-Pages Deploy
          command: ./node_modules/.bin/gh-pages -d public -r https://${GH_TOKEN}@github.com/issa/fairs.git -m "Updates [ci skip]"
workflows:
  version: 2
  build:
    jobs:
      - setup
      - build:
          requires:
            - setup
          filters:
            branches:
              only:
                - master
